namespace Gruas.API.Models.DTO.Reportes
{
    public class GetServiciosProveedorMensuales_Response
    {
        public Guid id { get; set; }
        public int folio {  get; set; }
        public int tipoServicioId { get; set; }
        public string tipoServicio { get; set; }
        public DateTime fecha { get; set; }
        public Guid clienteId { get; set; }
        public string clienteNombre { get; set; }
        public string clienteTelefono { get; set; }
        public Guid? municipioId { get; set; }
        public string? municipio {  get; set; }
        public string tipoVehiculo { get; set; }
        public string origenMunicipio { get; set; }
        public string origenDireccion { get; set; }
        public string origenLat {  get; set; }
        public string origenLon { get; set; }
        public string origenReferencia { get; set; }
        public string destinoMunicipio { get; set; }
        public string destinoDireccion { get; set; }
        public string destinoLat { get; set; }
        public string destinoLon { get; set; }
        public string destinoReferencia { get; set; }
        public bool vehiculoAccidentado { get; set; }
        public bool fugaCombustible { get; set; }
        public bool llantasGiran { get; set; }
        public bool puedeNeutral { get; set; }
        public int personasEnVehiculo { get; set; }
        public string lugarUbicuidad { get; set; }
        public int? carreteraCarril { get; set; }
        public int? carreteraKm {  get; set; }
        public string? carreteraDestino { get; set; }
        public string? estacionamientoTipo { get; set; }
        public string? estacionamientoPiso { get; set; }
        public string vehiculoMarca { get; set; }
        public int vehiculoAnio { get; set; }
        public string vehiculoColor {  get; set; }
        public string vehiculoCuentaPlacas { get; set; }
        public string vehiculoPlacas { get; set; }
        public bool vehiculoCuentaModificaciones { get; set; }
        public string vehiculoDescripcionModificaciones { get; set; }
        public decimal distancia { get; set; }
        public decimal cuotaKm { get; set; }
        public decimal banderazo { get; set; }
        public bool maniobras {  get; set; }
        public decimal maniobrasCosto { get; set; }
        public decimal totalSugerido { get; set; }
        public int estatusServicioId { get; set; }
        public string estatusServicio { get; set ;}
        public Guid? proveedorId { get; set; }
        public string? proveedorRfc {  get; set; }
        public string? proveedorTelefono { get; set; }
        public string? proveedorRazonSocial { get; set; }
        public Guid? gruaId { get; set; }
        public string? gruaPlacas { get; set; }
        public string? gruaMarca { get; set; }
        public string? gruaModelo { get; set; }
        public decimal? total {  get; set; }
        public decimal? tiempoLlegada { get; set; }
        public decimal? direccionCongestion { get; set; }
        public decimal? direccionKmsTotales { get; set; }
        public decimal? direccionMinsNormal { get; set; }
        public decimal? direccionMinsTrafico { get; set; }
        public string? motivoCancelacion { get; set; }
        public DateTime? fechaCancelacion { get; set; }
        public Guid? usuarioCancelacion { get; set; }
        public string? telefono {  get; set; }
        public string? correoElectronico { get; set; }
        public DateTime fechaCreacion { get; set; }
    }
}
